# brew => 'brew install <package>'
# cask => 'brew install --cask <package>'
# mas => 'mas install <package>'

brew "docker"
brew "docker-buildx"
brew "docker-compose"

brew "colima"

# brew "podman"
# brew "podman-compose"
# cask "podman-desktop"
# cask "rancher"

# brew zsh-autosuggestions
# brew zsh-autocomplete
# brew zsh-syntax-highlighting
brew "zimfw"
## cd  setup: https://github.com/ajeetdsouza/zoxide
brew "zoxide"
brew "asdf"

# brew "aws-vault"
brew "awscli"
brew "saml2aws"


# brew "direnv"
brew "fzf"
brew "gh"
#brew "httpie"
brew "jq"
brew "lazydocker"
brew "lazygit"
# brew "mas"
brew "navi"
brew "neovim"
brew "pipx"
# brew "reattach-to-user-namespace"
# brew "terminal-notifier"
# brew "thefuck"
brew "tmux"
# brew "watch"
brew "wget"

## cat
brew "bat"
## top
brew "bottom"
## du
# brew "dust"
## ls
brew "eza"
## find
brew "fd"
## git diff
brew "git-delta"
## reverse search
brew "mcfly"
## ps
brew "procs"
## grep
brew "ripgrep"
## tldr
brew "tealdeer"

# cask "alfred"
# cask "monarch"
cask "raycast"

## Terminal
# cask "alacritty"
# cask "iterm2"
# cask "kitty"
# cask "warp"
# cask "wezterm"
cask "ghostty"

# cask "flycut"
cask "maccy"

#cask "hoppscotch"
# cask "insomnia"
cask "postman"

# cask "craft"
# cask "notion"
cask "obsidian"

cask "sublime-text"
# cask "zed"

cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"

# cask "gitkraken"
# cask "fork"
cask "github"

# cask "itsycal"
# mas "dato"
cask "meetingbar"

cask "google-chrome"
cask "arc"
# cask "brave-browser"

cask "aldente"
# cask "appcleaner"
cask "bitwarden"
cask "chatgpt"
# cask "clocker"
# cask "cron"
cask "datagrip"
# cask "discord"
cask "espanso"
cask "hiddenbar"
cask "keka"
# cask "kekaexternalhelper"
# cask "iina"
# cask "openwebstart"  #support old version java
# cask "rectangle"
cask "slack"
cask "spotify"
# cask "stats"
# cask "steam"
cask "telegram"
cask "visual-studio-code"
cask "whatsapp"
cask "zoom"

#
# mas "Tailscale", id: 1475387142
# mas "befocused"
# mas "dropover"

