#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    #colorscheme = "sonokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    enable_neomake = false
    enable_ale = true
    autocomplete_method = "coc"
    filemanager = "vimfiler" 
    bootstrap_before = "myspacevim#before"
    snippet_engine = "ultisnips"

  
[[layers]]
  name = "default"

[[layers]]
  name = 'core'
  filetree_show_hidden = true

#Enable it when changing default colorscheme
#[[layers]]
#  name = "colorscheme"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = 'complete'
  auto_completion_tab_key_behavior = 'smart'

[[layers]]
  name = 'git'

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

#[[layers]]
#name = "tmux"

[[layers]]
  name = "fzf"

[[layers]]
  name = 'lsp'
  filetypes = [
    "javascript",
    "go"
  ]
  [layers.override_cmd]
    go = ["gopls", "serve"]

[[layers]]
  name = 'lang#go'
[[layers]]
  name = 'lang#json'
[[layers]]
  name = 'lang#markdown'
[[layers]]
  name = 'lang#yaml'

[[custom_plugins]]
  repo = 'sainnhe/sonokai'
  merged = 0

