# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH="/opt/homebrew/bin:$PATH"
#
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

export UPDATE_ZSH_DAYS=14

plugins=(
  # alias-finder
  # aws 
  # cross-platform background notifications for long running commands! Supports OSX and Ubuntu linux.
  # bgnotify
  # command-not-found 
  # This plugin adds the ctrl-o keyboard shortcut to copy the current text in the command line to the system clipboard.
  # copybuffer 
  # Copies the path of given directory or file to the system clipboard.
  # copypath
  # Puts the contents of a file in your system clipboard so you can paste it anywhere.
  # copyfile 
  # docker 
  # git 
  # history-substring-search 
  # iterm2 
  macos
  vi-mode 
  # web-search
  #git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  zsh-autosuggestions 
  #zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source $HOME/.zsh_aliases

NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$PATH:${HOME}/.local/bin"
export PATH="$PATH:${HOME}/Documents/scripts"
export PATH="$PATH:$NPM_PACKAGES/bin"

# Preserve MANPATH if you already defined it somewhere in your config.
# Otherwise, fall back to `manpath` so we can inherit from `/etc/manpath`.
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"

#test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# . /usr/local/opt/asdf/libexec/asdf.sh

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# pnpm
export PNPM_HOME="/Users/xiao/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

eval "$(zoxide init zsh)"
eval "$(mcfly init zsh)"


. /opt/homebrew/opt/asdf/libexec/asdf.sh
